/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trinkets_win32_shell_impl_IContextMenuImpl */

#ifndef _Included_org_trinkets_win32_shell_impl_IContextMenuImpl
#define _Included_org_trinkets_win32_shell_impl_IContextMenuImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trinkets_win32_shell_impl_IContextMenuImpl
 * Method:    getItems0
 * Signature: (Ljava/lang/String;)[Lorg/trinkets/win32/shell/IContextMenuItem;
 */
JNIEXPORT jobjectArray JNICALL Java_org_trinkets_win32_shell_impl_IContextMenuImpl_getItems0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_trinkets_win32_shell_impl_IContextMenuImpl
 * Method:    invokeItem0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_trinkets_win32_shell_impl_IContextMenuImpl_invokeItem0
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
