/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trinkets_win32_shell_IContextMenu_JNI */

#ifndef _Included_org_trinkets_win32_shell_IContextMenu_JNI
#define _Included_org_trinkets_win32_shell_IContextMenu_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trinkets_win32_shell_IContextMenu_JNI
 * Method:    getItems0
 * Signature: (Ljava/awt/Component;[Ljava/lang/String;[I)[Lorg/trinkets/win32/shell/IContextMenuItem;
 */
JNIEXPORT jobjectArray JNICALL Java_org_trinkets_win32_shell_IContextMenu_1JNI_getItems0
  (JNIEnv *, jobject, jobject, jobjectArray, jintArray);

/*
 * Class:     org_trinkets_win32_shell_IContextMenu_JNI
 * Method:    invokeItem0
 * Signature: (Ljava/awt/Component;[Ljava/lang/String;[II)V
 */
JNIEXPORT void JNICALL Java_org_trinkets_win32_shell_IContextMenu_1JNI_invokeItem0
  (JNIEnv *, jobject, jobject, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
